### ISSUE TITLE
Surface which components are available on npm under @financial-times namespace

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-repo-data#103]
We have lots of components on npm but not all components. It would be very useful for the registry to label which ones are on npm. I think this information should be in repo-data but I am not sure as it is not about the repo but is about the deployed artefact.

**Comment by chee** [comment]
We could add something to the release command of https://github.com/financial-times/origami-ci-tools to store it has published `name@version`... somewhere.

Or we could hit the npm api and check if `@financial-times/$name` exists...

**Comment by chee** [comment]
`if (circleConfig.jobs.publish_to_npm != null)` hahaha

**Comment by JakeChampion** [comment]
origami.json could contain a field which has a map/object, that way it is stored in the repo and we don't need to assume anything such as the published namespaces which are used on npm
E.G.
```
{
  "bower": "jake-component",
  "npm": "@jakechampion/component"
}
```

**Comment by chee** [comment]
true. though that does involve changes to at least `occ`, `origami-ci-tools` and the manifest specification in addition to `origami-repo-data` and having an `npm` field doesn't actually guarantee it's on npm.

**Comment by chee** [comment]
something that happens as a result of the publish actually taking place would be good, because then the data is tied to the event we're surfacing having taken place.
`origami-ci-tools` might be the best place for it. to an s3 bucket? something that says component's name at version has been published on npm as `@org/name@version`

**Comment by notlee** [comment]
@JakeChampion shall we close this issue now we're moving to npm only?
