### ISSUE TITLE
Feature: Webhook system

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-repo-data#121]
We have a few systems which want to update automatically based on Origami-wide changes such as:
- A brand new component is created (`origami-bower-registry`, `origami-build-service-v3`)
- A new release has happened on a component (Slack announcer in #ft-origami)

Currently these are all working by creating their own organisation GitHub webhook and having the same business logic to work out if something is an Origami component. We could replace this repeated integration and business logic by making Origami-Repo-Data implement it's own webhook system and using that instead of GitHub webhooks, that way the Origami-Repo-Data would contain the business logic once instead of repeating it across different codebases.

**Comment by chee** [comment]
this is a great idea, i'm 100% on board

**Comment by chee** [comment]
we'll not be doing any more feature work on repo-data
