### ISSUE TITLE
Proposal: remove API Key requirement for some endpoints

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-repo-data#126]
I think we should remove the API key requirement for some endpoints. A question raised in the past was whether this would expose sensitive information from private repositories, I think we can get around this by still requiring an API key for the endpoints which serve you a file (e.g manifest or README). I don't think exposing our processed meta information for a repo is a privacy/security risk.

Here's what I'm proposing:

```diff
  requires key with ADMIN perms  /v1/keys
  requires key with ADMIN perms  /v1/keys/:keyId
  requires key with WRITE perms  /v1/queue
  requires key with READ perms   /v1/queue
  requires key with READ perms   /v1/queue/:ingestionId
  requires key with ADMIN perms  /v1/queue/:ingestionId
- requires key with READ perms   /v1/repos
+ requires no key                /v1/repos
- requires key with READ perms   /v1/repos/:repoId
+ requires no key                /v1/repos/:repoId
- requires key with READ perms   /v1/repos/:repoId/versions
+ requires no key                /v1/repos/:repoId/versions
- requires key with READ perms   /v1/repos/:repoId/versions/:versionId
+ requires no key                /v1/repos/:repoId/versions/:versionId
  requires key with READ perms   /v1/repos/:repoId/versions/:versionId/manifests/:manifestType
  requires key with READ perms   /v1/repos/:repoId/versions/:versionId/markdown/:markdownType
- requires key with READ perms   /v1/repos/:repoId/versions/:versionId/demos
+ requires no key                /v1/repos/:repoId/versions/:versionId/demos
- requires key with READ perms   /v1/repos/:repoId/versions/:versionId/images
+ requires no key                /v1/repos/:repoId/versions/:versionId/images
  requires key with READ perms   /v1/repos/:repoId/versions/:versionId/dependencies
- requires key with READ perms   /v1/repos/:repoId/versions/:versionId/bundles/:language
+ requires no key                /v1/repos/:repoId/versions/:versionId/bundles/:language
```

I've made all of the endpoints which return `Repository`, `Version`, `Demo`, `Image`, or `Bundle` entities require no API key. I've left the `Manifest` and `Markdown` endpoints as-is, because these may contain information we don't want to be available to unauthenticated requests.

**Comment by notlee** [comment]
The bundle size ci tool needs access to the origami manifest so we'd still need access tokens in CircleCI. Another thing to consider is attribution. If we remove the need for an api key we should probably introduce a source param as with our other public services.

What are the other usecases which would be helped if we removed the need for an API key on these endpoints? I'm wondering now if it's worth while.

**Comment by notlee** [comment]
Closing this because it's done 🎉
