### ISSUE TITLE
Solutions for origamiType being component

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-repo-data#138]
I'm currently working out what we'd need to do to allow `origamiType` to be set to `component`, as outlined in [this proposal](https://github.com/Financial-Times/origami/issues/35). I think there are a couple of solutions, I'd like your thoughts on these, or potential other solutions.

## Solution 1: Consistent Data (`module`)

We allow an `origamiType` of `component` in our manifest files, but when repo-data encounters this it will store it in the database as `module`. Consumers of this service will only ever see a type of `module`.

### Pros
- Very little work to do in this repo (just add something to [manifest normalisation](https://github.com/Financial-Times/origami-repo-data/blob/master/models/version.js#L690))
- No work to do in [registry-ui](https://github.com/Financial-Times/origami-registry-ui)
- If `component` ever becomes the standard, we can migrate all versions at once

### Cons

- The database doesn't accurately represent the manifest for components (I don't think it does exactly now though anyway)
- We still need to keep it in our heads that `module` means `component` for a while longer, at least until we have a version of the spec that removes `module`
- We're not really _deprecating_ a type of `module`, we're creating an alias

## Solution 2: Inconsistent Data

We allow an `origamiType` of `component` in our manifest files, repo-data will store it in the database as `component`. Consumers of this service will see a mix of `component` and `module` types.

### Pros
- The database more accurately represents the manifest for components

### Cons

- A fair bit of work to do in this repo, based on searching for places that the `origamiType` is used
- We'd need to update [registry-ui](https://github.com/Financial-Times/origami-registry-ui) first to properly handle the new types
- Other tools which rely on repo-data (e.g. when we're making origami-wide changes) will need to consider the new type
- We still need to keep it in our heads that `module` means `component` for a while longer, at least until we have a version of the spec that removes `module`

## Solution 3: Consistent Data (`component`)

We allow an `origamiType` of `component` in our manifest files, repo-data will store it in the database as `component` and will also convert `module` to `component`. We will update all existing `module` types to `component`. Consumers of this service will see only `component` types.

### Pros
- We've properly deprecated a `type` of `module`

### Cons

- A fair bit of work to do in this repo, based on searching for places that the `origamiType` is used, and a large migration
- This would be a breaking change to the API, and we'd need to release v2
- We'd need to update [registry-ui](https://github.com/Financial-Times/origami-registry-ui) once the new API is in place

**Comment by JakeChampion** [comment]
I'm in favour of both 1 and 3, happy for either one to be chosen 👍

**Comment by notlee** [comment]
Also happy with either 1 or 3. Prefer 3, but appreciate the con of how much more work that is

**Comment by rowanmanning** [comment]
I think I'm gonna go with solution 1, as it gets us one step closer to removing `module` in a quick and easy way. It's quite a lot more work to create and release a v2, and it's either introducing a lot of copy/paste or requiring us to work out how we share a lot of the logic in the routes between two different API versions. It also doesn't prevent us from implementing solution 3 later.
