### ISSUE TITLE
Update for most recent spec v2 changes

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-repo-data#335]
E.g. support contacts are moved to package.json, origamiType is now origami, origamiVersion is now version, etc:
https://docs.google.com/document/d/1cKJKkRTeG_uyvoCtx8E-dZSpaIcwoPE0ScepLcsSrr0/edit#

**Comment by chee** [comment]
this isn't needed now, right?

**Comment by JakeChampion** [comment]
That's right, closing the issue 👍
