### ISSUE TITLE
Include the changelog in Slack annoucement

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-repo-data#346]
Components now have a [changelog](https://github.com/Financial-Times/origami/blob/main/components/o-colors/CHANGELOG.md). Include details from the changelog in the Slack announcement for the latest version ingested.
https://github.com/Financial-Times/origami-repo-data/blob/5c49fa79697b339b76b60ac22b6bd88313e7ffc0/lib/ingestion-queue-processor.js#L61
<img width="565" alt="Screenshot 2021-09-24 at 17 50 52" src="https://user-images.githubusercontent.com/10405691/134712498-7fe35a35-802d-4c5f-9156-747c19403fbd.png">

**Comment by chee** [comment]
#349
